export const FETCH_COINS_REQUEST = 'FETCH_COINS_REQUEST';
export const FETCH_COINS_SUCCESS = 'FETCH_COINS_SUCCESS';
export const FETCH_SINGLE_COIN_SUCCESS = 'FETCH_SINGLE_COIN_SUCCESS';
export const FETCH_COINS_ERROR = 'FETCH_COINS_ERROR';
